### ISSUE TITLE
Make it clearer you can tap on an item to view its product page

### ISSUE THREAD

**Issue by SheaSmith** [SheaSmith/COSC345-Project#96]
Currently it is unclear to users that you can view information about a product by tapping on its card. They think you can only click the add to shopping list button.

**Comment by SheaSmith** [comment]
Kinda solved by #110, as that differentiates the clickable product card from the buttons. Still need to discuss banner message

**Comment by jgmarshall2001** [comment]
Shea changed design of product cards to make it more obvious they can be tapped.
